#!/bin/bash
# https://github.com/hippie68/pkgrename
# Renames PS4 PKG files based on param.sfo information and predefined patterns.
# Requires script "sfo" (https://github.com/hippie68/sfo) in $PATH.

# If you have renamed "sfo", enter the correct name here:
sfo_script_name=sfo

#########################
# Customization section:

# How the filename should look like:
pattern='$title [$category] [$filesize] [$title_id] [$releasegroup] [$release] [$backport].pkg'
# Possible variables:
#   title, category, sdk, firmware, releasegroup, release, backport
# Plus original SFO strings: app_ver, content_id, title_id, version

# Replacement for characters that would be invalid on an exFAT file system:
exfat_placeholder=_

# Do title customization here:
# e.g. title=${title//SEARCH/REPLACE}
customize_title() {
  title=${title//[®™]/}
  title=${title//–/-}
  title=${title//’/\'}
  title=${title//＆/&}
  # Replace irregular whitespace with regular one:
  title=${title// / }
  # Uncomment these lines if you want placeholders for : and & to disappear:
  #title=${title//:/}; title=${title//  / }
  #if [[ $title == *[a-z]* ]]; then
  #  title=${title// & / and }
  #else
  #  title=${title// & / AND }
  #fi
}

# Do all other file name customization here:
customize() {
  # How different categories should look like:
  category_game="Game"
  category_patch="Update v${app_ver#0}"
  category_dlc="DLC"
  # Optional: characters to remove should a variable be empty:
  outer_shell="[]"
}

#######################
# Script starts below:

show_usage() {
  echo "Usage: ${0##*/} [-fhor] [file/directory ...]" >&2
}

show_help() {
  show_usage 2>&1
  echo "
  Automatically renames PKG files based on customizable patterns.
  Customization takes place inside the script file.
  If no files or directories are specified, the current directory will be used.

  Options:
    -f  Force prompt when file name matches pattern
    -h  Display this help info
    -o  Default to online search
    -r  Traverse directories recursively"
  exit
}

find_option="-maxdepth 1"

# Parse command line options
while [[ $1 == "-"?* ]]; do
  for ((i=1;i<${#1};i++)); do
    case ${1:$i:1} in
      f) force_prompt=true ;;
      h) show_help ;;
      o) search_ps_store=true ;;
      r) find_option= ;;
      *) show_usage; exit 1 ;;
    esac
  done
  shift
done

[[ $1 == "" ]] && set -- '.' # Use current directory if no arguments given

cleanup() {
  echo "Script aborted."
  exit
}

trap '{ echo; cleanup; }' SIGINT

# Prints a message and reads a keystroke until input is valid
# $1: Message, $2: Allowed characters
read_userinput() {
  local char
  while read -e -t 0.01; do true; done # Clear buffer
  while [[ ${char,,} != [$2] ]]; do
    read -p "$1 " -n 1 char
    while read -e -t 0.01; do true; done
    echo
  done
  userinput=${char,,}
}

# Optionally searches the PS Store for better titles (option -s)
online_search() {
  case $content_id in
    UP*) url="https://store.playstation.com/en-us/product/$content_id" ;;
    EP*) url="https://store.playstation.com/en-gb/product/$content_id" ;;
    JP*) url="https://store.playstation.com/ja-jp/product/$content_id" ;;
    *) return ;;
  esac
  online_search_result=$(curl --silent "$url" \
    | grep -Po -m1 '"@type":"Product","name":"\K[^"]*(?=")')
  if [[ $online_search_result == "" ]]; then
    echo "Online search failed." >&2
  else
    title=$online_search_result
    echo "Online search successful."
  fi
}

# Moves file "$1" to new file name "$2"
rename_file() {
  # Skip if filenames are equal
  if [[ $1 == "$2" ]]; then
    echo "Nothing to do."
    return 0 # Skip to next PKG
  fi

  # Skip if new file name is an existing directory
  if [[ -d "$2" ]]; then
    echo "A directory with the same name already exists." >&2
    echo "Skipped file $1" >&2
    rename_all=false
    return 1 # Return to interactive loop with current PKG
  fi

  if [[ -f "$2" ]]; then
    # Filesystem is case-insensitive (e.g. exFAT)
    if [[ ${1,,} == "${2,,}" ]]; then
      if [[ -f "$1.pkgrename" ]]; then
        echo "The old temporary file \"$1.pkgrename\" prevents renaming." >&2
        echo "Please fix this and then try again." >&2
        return 1
      else
        # Workaround for mv on case-insensitive filesystems
        mv "$1" "$1.pkgrename" && mv "$1.pkgrename" "$2"
      fi
    # Filesystem is case-sensitive
    else
      echo "File \"$2\" already exists."
      read_userinput "Overwrite? [Y]es [N]o" yn
      case $userinput in
        y) mv "$1" "$2" ;;
        n) return 1 ;;
      esac
    fi
  else
    mv -i "$1" "$2"
  fi
}

# Accepts a PKG file and renames it
pkgrename() {
  local app_ver backport category content_id firmware newfilename \
    online_search_result pubtoolinfo release releasegroup sdk title title_id \
    version
  echo "${1##*/}"

  # Run external "sfo" script to get param.sfo variables
  while IFS= read -r line; do
    case "${line%%=*}" in
      APP_VER) app_ver=${line#*=} ;; # Patch version
      CATEGORY) category=${line#*=} ;; # ac: DLC, gd: Game, gp: Patch
      CONTENT_ID) content_id=${line#*=} ;; # https://www.psdevwiki.com/ps4/Content_ID
      PUBTOOLINFO) pubtoolinfo=${line#*=} ;;
      SYSTEM_VER)
        firmware=${line#*0x}
        firmware=${firmware:0:2}.${firmware:2:2}
        firmware=${firmware#0}
        (( ${firmware/./} )) || firmware= # Set empty if not a number
        ;;
      TITLE) title=${line#*=} ;; # Game/Patch/DLC name
      TITLE_ID) title_id=${line#*=} ;; # CUSAXXXXX
      VERSION) version=${line#*=} ;; # Master version
    esac
  done < <("$sfo_script_name" "$1")

  # Create "sdk" variable (stays empty if PKG is DLC)
  if [[ $category == +(gd|gp) ]]; then
    sdk=${pubtoolinfo#*sdk_ver=}
    sdk=${sdk%%,*}
    sdk=${sdk:0:2}.${sdk:2:2}
    sdk=${sdk#0}
    (( ${sdk/./} )) || sdk= # Set empty if not a number
  fi

  # Check for backport
  # Compare sdk and firmware; could generate false positives (hopefully not)
  if [[ $sdk == 5.05 && ${firmware/./} -gt 600 ]]; then
    backport=Backport
  fi

  # Check file name for release groups
  case ${1,,} in
    *[^a-z]bigbluebox[^a-z]*) releasegroup="BigBlueBox" ;;
    *[^a-z]blz[^a-z]*|*[^a-z]blaze[^a-z]*) releasegroup="BlaZe" ;;
    *[^a-z]caf[^a-z]*) releasegroup="CAF" ;;
    *[^a-z]darkmoon[^a-z]*) releasegroup="DarKmooN" ;;
    *[^a-z]duplex[^a-z]*) releasegroup="DUPLEX" ;;
    *[^a-z]gcmr[^a-z]*) releasegroup="GCMR" ;;
    *[^a-z]hoodlum[^a-z]*) releasegroup="HOODLUM" ;;
    *[^a-z]hr[^a-z]*) releasegroup="HR" ;;
    *[^a-z]jrp[^a-z]*) releasegroup="JRP" ;;
    *[^a-z]kotf[^a-z]*) releasegroup="KOTF" ;;
    *[^a-z]levelup[^a-z]*) releasegroup="LevelUp" ;;
    *[^a-z]lfc[^a-z]*|*[^a-z]lightforce[^a-z]*) releasegroup="LiGHTFORCE" ;;
    *[^a-z]marvtm[^a-z]*) releasegroup="MarvTM" ;;
    *[^a-z]moemoe[^a-z]*) releasegroup="MOEMOE" ;;
    *[^a-z]playable[^a-z]*) releasegroup="Playable" ;;
    *[^a-z]prelude[^a-z]*) releasegroup="PRELUDE" ;;
    *[^a-z]protocol[^a-z]*) releasegroup="PROTOCOL" ;;
    *[^a-z]respawn[^a-z]*) releasegroup="RESPAWN" ;;
    *[^a-z]sharphd[^a-z]*) releasegroup="SharpHD" ;;
    *[^a-z]tcd[^a-z]*) releasegroup="TCD" ;;
    *[^a-z]unlimited[^a-z]*) releasegroup="UNLiMiTED" ;;
    *[^a-z]walmart[^a-z]*) releasegroup="WaLMaRT" ;;
    *[^a-z]waysted[^a-z]*) releasegroup="WaYsTeD" ;;
  esac

  # Other releases
  case ${1,,} in
    *[^a-z]arczi[^a-z]*) release="Arczi" ;;
    *[^a-z]opoisso893[^a-z]*) release="OPOISSO893" ;;
    *[^a-z]cyb1k[^a-z]*) release="CyB1K" ;;
  esac

  # This line is option "-o", must be run before title customization
  [[ $search_ps_store == true ]] && online_search

  # Apply user's customization
  customize_title
  title_backup=$title # Backup for possible use of [R]eset
  customize
  case "$category" in
    ac) category="$category_dlc" ;;
    gd) category="$category_game" ;;
    gp) category="$category_patch" ;;
    *) category="Unknown category" ;;
  esac

  # Interactive loop
  while true; do
    # Apply user's pattern
    newfilename=$(eval echo "$pattern")

    # Remove outer shell characters and whitespace caused by empty variables
    newfilename=${newfilename//$outer_shell/}
    newfilename=${newfilename//  / }
    newfilename=${newfilename/ ./.}

    # Encforce exFAT compatibility
    # (https://www.ntfs.com/exfat-filename-dentry.htm)
    newfilename=${newfilename//[&:\\|\/\"<>*]/$exfat_placeholder}

    echo "$newfilename"
    if [[ $newfilename == "${1##*/}" && $force_prompt != true ]]; then
      echo "Nothing to do."
      break
    elif [[ $rename_all == true ]]; then
      if rename_file "$1" "$(dirname "$1")/$newfilename"; then
        break
      else
        continue
      fi
    else
      read_userinput "Rename? [Y]es [N]o [A]ll [E]dit [M]ix [O]nline [R]eset [C]hars [S]FO [Q]uit:" ynaemorcsq
      case $userinput in
        y)
          if rename_file "$1" "$(dirname "$1")/$newfilename"; then
            break
          else
            continue
          fi
          ;;
        n) break ;;
        a)
          if rename_file "$1" "$(dirname "$1")/$newfilename"; then
            rename_all=true
            break
          else
            continue
          fi
          ;;
        e) echo "Enter new title:"; read -i "$title" -e title ;;
        m)
          title=${title,,}
          array=($title)
          title=${array[@]~} # Uppercase for first letter of every word
          echo "Converted title to mixed-case style."
          ;;
        o) online_search; customize_title ;;
        r) title=$title_backup; echo "All changes reset." ;;
        c)
          special_chars=$(echo -n "$newfilename" | cat -A);
          if [[ $special_chars != "$newfilename" ]]; then
            echo "Special characters found:"
            echo "$special_chars"
          else
            echo "No special characters found."
          fi
          ;;
        s) echo; "$sfo_script_name" "$1"; echo ;;
        q) cleanup ;;
      esac
    fi
  done
  echo
}

# File loop
while [[ $1 != "" ]]; do
  if [[ -d "$1" ]]; then
    # File descriptor 3 because of nested reads (function "read_userinput")
    while IFS= read -r -d $'\0' -u 3 pkg; do
      pkgrename "$pkg"
    done 3< <(find "$1" $find_option -iname '*.pkg' -type f -print0 | sort -z)
  elif [[ -f "$1" && ${1,,} == *.pkg ]]; then
    pkgrename "$1"
  fi
  shift
done
